deletions:
  - .github/workflows/repo-sync.yaml
ignore:
  - version.properties
  - app/src/main/res/drawable/ic_app.xml
  - app/src/main/res/drawable/ic_logo.xml
replacements:
  - from: "PERSONACLICK_COURIER_SECRET"
    to: "PERSONACLICK_COURIER_SECRET"
  - from: "PERSONACLICK_COURIER_ID"
    to: "PERSONACLICK_COURIER_ID"
  - from: "https://personaclick.atlassian.net/wiki/spaces/english/overview?mode=global"
    to: "https://personaclick.atlassian.net/wiki/spaces/english/overview?mode=global"
  - from: "success@personaclick.com"
    to: "success@personaclick.com"
  - from: 42a4cd11ebab3b0454778d18d4f3d5
    to: 42a4cd11ebab3b0454778d18d4f3d5
  - from: 5a57812604806d58d3d98f8e9480cb97
    to: 5a57812604806d58d3d98f8e9480cb97
  - from: e4fd6e3a19610f7aea5534e96eec69d6
    to: e4fd6e3a19610f7aea5534e96eec69d6
  - from: 5a57812604806d58d3d98f8e9480cb97
    to: aabc899d3db3d71c4032832e4291c16a
  - from: 09d291f54de95e9e5bde43b343b0b0d7
    to: 09d291f54de95e9e5bde43b343b0b0d7
  - from: https://api.personaclick.com/
    to: https://api.personaclick.com/
  - from: com.personaclick:personaclick-sdk
    to: com.personaclick:personaclick-sdk
  - from: api.personaclick.com
    to: api.personaclick.com
  - from: personaclick.com
    to: personaclick.com
  - from: personaclick
    to: personaclick
  - from: PersonaClick
    to: PersonaClick
  - from: PersonaClick
    to: PersonaClick
