name: Publish to Play Store

on:
  pull_request:
  # TODO
  #   types:
  #     - closed
  #   branches:
  #     - master
  # workflow_dispatch:

jobs:
  google-play-publish:
    # if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    # uses: personaclick/workflow/.github/workflows/reusable-android-google-play-publish.yaml@1cfee7e2e762eed3a3d7d67c413aa0bae7f5ffae
    # TODO replacements
    uses: personaclick/workflow/.github/workflows/reusable-android-google-play-publish.yaml@d6d23e924224f75a134a47b364002c48bf0c88da
    with:
      githubAppId: ${{ vars.PERSONACLICK_COURIER_ID }}
      packageName: "personaclick.demo_shop"
      aabReleasePath: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
      propertiesFilePath: "version.properties"
    secrets:
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
      GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
      GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}
      RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
