name: Publish to Play Store and Bump Version

on:
  # TODO uncomment
  pull_request:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed
  # workflow_dispatch:

env:
  PACKAGE_NAME: "personaClick.demo_shop"
  AAB_RELEASE_PATH: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
  PROPERTIES_FILE_PATH: "version.properties"

jobs:
  publish_and_version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and create google-services.json
        run: |
          mkdir -p app/src/prod/release
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/src/prod/release/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

      - name: Decode Google Play service account JSON
        id: decode
        run: |
          echo "${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}" | base64 --decode > google-play-service-account.json
          playJson=$(cat google-play-service-account.json)

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_AS_BASE64" | base64 --decode > app/keystore.jks
        env:
          KEYSTORE_AS_BASE64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: "20"
          distribution: "zulu"

      # Building release bundle
      - name: Build Release AAB
        run: ./gradlew bundleProdRelease
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/app/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      # Sending to Google Play
      - name: Deploy to Google Play Internal Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google-play-service-account.json
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ github.workspace }}/${{ env.AAB_RELEASE_PATH}}
          track: "internal"

      # Increment version
      - name: Bump version
        run: ./gradlew incrementVersion
        env:
          PROPERTIES_FILE: ${{ env.PROPERTIES_FILE_PATH }}
          SIGNING_STORE_FILE: ${{ github.workspace }}/app/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      # Getting new version
      - name: Retrieve new version
        id: versionName
        run: |
          version=$(grep "VERSION_NAME=" ${{ env.PROPERTIES_FILE_PATH }} | cut -d'=' -f2)
          echo "versionName=$version" >> $GITHUB_ENV
          echo "versionName=$version" >> $GITHUB_OUTPUT

      # Commit changes
      - name: Commit changes
        id: committer
        uses: planetscale/ghcommit-action@v0.1.44
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: "chore: bump version to ${{ steps.versionName.outputs.versionName }}"
          file_pattern: ${{ env.PROPERTIES_FILE_PATH }}
