name: Sync original repository

on:
  repository_dispatch:
    types: [sync]
  workflow_dispatch:

jobs:
  run:
    name: Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: kirill-ivanovvv
          repositories: trigger-repository

      - name: Sync Files
        uses: ./.github/actions/sync-repo # Локальный экшен
        with:
          source_repo: "https://github.com/kirill-ivanovvv/trigger-repository"
          source_branch: "main"
          github_token: ${{ steps.app-token.outputs.token }}
