name: Sync original repository

on:
  repository_dispatch:
    types: [sync]
  workflow_dispatch:

jobs:
  run:
    name: Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: kirill-ivanovvv
          repositories: trigger-repository

      - name: Find base commit
        id: base_commit
        uses: rees46/workflow/.github/actions/js/find-base-commit-js@master
        with:
          token: ${{ steps.start.outputs.token }}

      - name: Sync Files
        uses: ./.github/actions/sync-repo # Локальный экшен
        with:
          source_repo: "https://github.com/kirill-ivanovvv/trigger-repository"
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Commit changes
        if: ${{ !contains(github.event.pull_request.title, 'revert') && !contains(github.event.pull_request.title, 'chore') && !cancelled() }}
        uses: rees46/workflow/.github/actions/js/commit-js@master
        with:
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          token: ${{ steps.app-token.outputs.token }}
          exclude: "."
